<a href="https://colab.research.google.com/github/hyndhavialigeri/FMML_Machine_learning-2023/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 0:
write down 3-5 methods applicable to each data type. (Hint: extend, reverse, etc.

In [ ]:
'List'
list=[1, 2, 'A', 'bcd', 'List-example','A']
id=list.index(2)
c=list.count('A')
p=list.pop(5)

print(id)
print(c)
print(p)

1
2
A


In [ ]:
'tuples'
tuple=(1,3,6,2,7,9)
idx=tuple.index(2)
maxi=max(tuple)
mini=min(tuple)

print(maxi)
print(mini)
print(idx)

9
1
3


In [ ]:
'set'
set1={1,4,6,8,0}
set2={1,3,5,7,9}
cop=set1.copy()
diff=set1.difference(set2)

print(cop)
print(diff)
set1.discard(0)
print(set1)

{0, 1, 4, 6, 8}
{0, 8, 4, 6}
{1, 4, 6, 8}


In [ ]:
'dictionary'
dictionary={'Name1':'Harry', 'Name2':'Ema', 'Name3':'Ron'}
print(dictionary.get('Name1'))
keys=dictionary.keys()
print(keys)
val=dictionary.values()
print(val)

Harry
dict_keys(['Name1', 'Name2', 'Name3'])
dict_values(['Harry', 'Ema', 'Ron'])


Question 1 :
Define a function, which takes in two strings A and B. Reverses the first string A, adds it to B, and returns the final string.

In [ ]:
def final_string(A,B):
  A=A[::-1]
  final=A+B
  return final
ans=final_string('Hyndhavi','Shetty')
print(ans)

ivahdnyHShetty


Question 2 :
Given a list having Names, work_hours, and gender, Write a function to print name of the female worker that worked the most hours. Also how much do should she be paid if the pay is $ 20 per hour.
work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]
Answer : the female worker that worked the most hours is Penny and she should be paid 18400

In [6]:
def find_max_work(work_hrs):
  maxi=0
  worker_name=None
  for name, hours, gender in work_hrs:
    if gender=='F' and hours>maxi:
      maxi=hours
      worker_name=name
  return worker_name, maxi
work_hrs=[('Abby',100,'F'),('Billy',400,'M'),('Cassie',800,'F'),('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]
worker_name, maxi=find_max_work(work_hrs)
print("The female worker that worked the most hours is ",worker_name," and should be paid ",(maxi*20))


The female worker that worked the most hours is  Penny  and should be paid  18400


Question 3 :
a)Create a 5x5 matrix of the following form,
[[1,1]
[2,2]]
i.e. each row is increasing and has repetive elements.
Hint : you can use hstack, vstack etc.

In [3]:
import numpy as np
arr=np.array([1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,4,4,4,4,4,5,5,5,5,5]).reshape(5,5)
print(arr)

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


find dot product of the matrix with any matrix. (Figure out the size/ shape of the matrix)

In [27]:
import numpy as np
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
result=ar1.dot(ar2)
print(result)

32
